import Link from 'next/Link'

export default function About() {
    return (
      <>
        <Head>
          <title>About</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Link href="http://localhost:3000">Go Back</Link>
        </main>
      </>
    )
  }
  